name: grocery_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins: # Add this if not present, flutter_stripe_web needs it
    sdk: flutter

  # UI/Utility Packages
  cupertino_icons: ^1.0.6 # Updated to latest stable
  shared_preferences: ^2.2.2 # Updated to latest stable
  provider: ^6.1.2 # Updated to latest stable
  flutter_iconly: ^1.0.2 # Seems okay, latest stable
  card_swiper: ^3.0.1 # Updated to latest stable
  fancy_shimmer_image: ^2.0.3 # Updated to latest stable
  flutter_staggered_grid_view: ^0.7.0 # Updated to latest stable
  badges: ^3.1.2 # Seems okay, latest stable
  flutter_spinkit: ^5.2.1 # Updated to latest stable
  fluttertoast: ^8.2.4 # Updated to latest stable
  uuid: ^4.3.3 # Updated to latest stable
  http: ^0.13.6  # Add this line
  flutter_dotenv: ^5.1.0 # Seems okay, latest stable
  readmore: ^2.2.0 # Or the latest version
  flutter_rating_bar: ^4.0.1 # Added for rating functionality

  # Firebase Core (Upgrade to latest stable)
  firebase_core: ^3.1.0 # Example: Use latest stable version

  # Firebase Auth (Upgrade to latest stable)
  firebase_auth: ^5.0.0 # Example: Use latest stable version matching core
  firebase_auth_web: ^5.14.2 # Use latest stable version found

  # Cloud Firestore (Upgrade to latest stable)
  cloud_firestore: ^5.0.0 # Example: Use latest stable version matching core
  cloud_firestore_web: ^4.0.0 # Example: Use latest stable version found

  # Other Firebase/Google Services
  google_sign_in: ^6.2.1 # Updated to latest stable

  # Stripe (Revert to latest stable)
  flutter_stripe: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Add flutter_lints as recommended
  flutter_lints: ^3.0.1 # LATEST STABLE

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ # Includes files directly in images/
    - assets/images/offres/ # Includes files in images/offers/
    - assets/images/landing/ # Includes files in images/landing/
    - assets/images/cat/ # Includes files in images/cat/
    - assets/images/add-to-cart.png
    - assets/images/basket.png
    - assets/images/box.png
    - assets/images/cart.png
    - assets/images/google.png
    - assets/images/history.png
    - assets/images/warning-sign.png
    - assets/images/wishlist.png

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages