// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH8CT5Fpu5V36XyaCCK5vgW_TSKAPU-ho',
    appId: '1:84274056941:web:1f2a95a63ddbf304ed86e4',
    messagingSenderId: '84274056941',
    projectId: 'grocery-app-2ba5c',
    authDomain: 'grocery-app-2ba5c.firebaseapp.com',
    storageBucket: 'grocery-app-2ba5c.firebasestorage.app',
    measurementId: 'G-CM3VXV5GGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1leMpavA-bOfYq8Hd7ATOKIEuXu__ae4',
    appId: '1:84274056941:android:fe2221df10bd5935ed86e4',
    messagingSenderId: '84274056941',
    projectId: 'grocery-app-2ba5c',
    storageBucket: 'grocery-app-2ba5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2T-36wYgo28e34ID8Cgp0lpzozgwBDM8',
    appId: '1:84274056941:ios:4549dad40d20ccd8ed86e4',
    messagingSenderId: '84274056941',
    projectId: 'grocery-app-2ba5c',
    storageBucket: 'grocery-app-2ba5c.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

}